name: Continuous Integration

on:
  push:
    branches: [main]

env:
  CI_COMMIT_ID: ${{ github.sha }}
  CI_REPO_NAME: ${{ github.repository }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  NPM_TOKEN: ${{ secrets.NPM_DEPLOYER_TOKEN }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: server

    steps:
      - uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache-dependency-path: 'package-lock.json'
          cache: 'npm'
      - name: Npm install
        run: npm ci
      - name: Lint
        run: npm run lint

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
