name: Continuous Integration

on:
  push:
    branches: [main]

env:
  BASE_URL: 'http://localhost:8080'
  MONGODB_URL: 'mongodb://root:rootpassword@localhost:27017/admin'
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  NPM_TOKEN: ${{ secrets.NPM_DEPLOYER_TOKEN }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache-dependency-path: 'package-lock.json'
          cache: 'npm'
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 4.2
          mongodb-port: 27017
          mongodb-username: 'root'
          mongodb-password: 'rootpassword'
          mongodb-db: 'admin'
      - name: Npm install
        run: npm ci
      - name: Lint
        run: npm run lint

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
